[service]
    filesystem = "${PF_FILESYSTEM}" # Could be "local" or "s3"
    s3_access_key = "${PF_S3_ACCESS_KEY}" # Mandatory for "s3" filesystem
    s3_secret_key = "${PF_S3_SECRET_KEY}" # Mandatory for "s3" filesystem
    s3_bucket = "${PF_S3_BUCKET}" # Mandatory for "s3" filesystem
    s3_region = "${PF_S3_REGION}" # Mandatory for "s3" filesystem
    path = "${PF_TEMP_PATH}"

[server]
    bind_address = "${PF_WS_HOST}"
    bind_port = ${PF_WS_PORT}

[redis]
    host = "${PF_REDIS_HOST}"
    port = ${PF_REDIS_PORT}

[sentry]
    dsn = "${PF_SENTRY_DSN}"
